/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Usuario;
import com.mycompany.banconegocio.Controlador.Control;
import com.mycompany.bancopersistencia.DAO.ClienteDAO;
import com.mycompany.bancopersistencia.excepciones.persistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmCrearUsuario2 extends javax.swing.JFrame {

    Control controlador = new Control();
    Cliente cliente;

    /**
     * Creates new form frmInicioSesion
     */
    public frmCrearUsuario2() {
        initComponents();
        textCalle.setBackground(new java.awt.Color(0, 0, 0, 1));
        textColonia.setBackground(new java.awt.Color(0, 0, 0, 1));
        textNumCasa.setBackground(new java.awt.Color(0, 0, 0, 1));
        fieldContra.setBackground(new java.awt.Color(0, 0, 0, 1));
        textNombreUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        fieldContraVerificar.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    public frmCrearUsuario2(Cliente cliente) {
        initComponents();
        textCalle.setBackground(new java.awt.Color(0, 0, 0, 1));
        textColonia.setBackground(new java.awt.Color(0, 0, 0, 1));
        textNumCasa.setBackground(new java.awt.Color(0, 0, 0, 1));
        fieldContra.setBackground(new java.awt.Color(0, 0, 0, 1));
        textNombreUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        fieldContraVerificar.setBackground(new java.awt.Color(0, 0, 0, 1));
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearCuenta = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        textCalle = new javax.swing.JTextField();
        textColonia = new javax.swing.JTextField();
        textNumCasa = new javax.swing.JTextField();
        textNombreUsuario = new javax.swing.JTextField();
        fieldContraVerificar = new javax.swing.JPasswordField();
        fieldContra = new javax.swing.JPasswordField();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1084, 773));
        setMinimumSize(new java.awt.Dimension(1084, 773));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCrearCuenta.setContentAreaFilled(false);
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 300, 60));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 170, 60));

        textCalle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textCalle.setForeground(new java.awt.Color(102, 102, 102));
        textCalle.setToolTipText("");
        textCalle.setBorder(null);
        getContentPane().add(textCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 450, 40));

        textColonia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textColonia.setForeground(new java.awt.Color(102, 102, 102));
        textColonia.setToolTipText("");
        textColonia.setBorder(null);
        textColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColoniaActionPerformed(evt);
            }
        });
        getContentPane().add(textColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 450, 40));

        textNumCasa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textNumCasa.setForeground(new java.awt.Color(102, 102, 102));
        textNumCasa.setToolTipText("");
        textNumCasa.setBorder(null);
        getContentPane().add(textNumCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 450, 40));

        textNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textNombreUsuario.setToolTipText("");
        textNombreUsuario.setBorder(null);
        getContentPane().add(textNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 450, 40));

        fieldContraVerificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fieldContraVerificar.setBorder(null);
        getContentPane().add(fieldContraVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 450, 40));

        fieldContra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fieldContra.setBorder(null);
        getContentPane().add(fieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 450, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Crear Usuario 2.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        labelFondo.setMaximumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setMinimumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setPreferredSize(new java.awt.Dimension(1080, 773));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        cliente.setCalle(textCalle.getText());
        cliente.setColonia(textColonia.getText());
        cliente.setNumeroCasa(Integer.parseInt(textNumCasa.getText()));
        frmCrearUsuario frmUsuario = new frmCrearUsuario(cliente);
        frmUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        String contra = new String(fieldContra.getPassword());
        String contraVerificar = new String(fieldContraVerificar.getPassword());
        try {
            if (!contra.equalsIgnoreCase(contraVerificar)) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no concuerdan entre si", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                cliente.setCalle(textCalle.getText());
                cliente.setColonia(textColonia.getText());
                cliente.setNumeroCasa(Integer.parseInt(textNumCasa.getText()));
                cliente.setContrasena(contra);
                cliente.setUsuario(textNombreUsuario.getText());
                controlador.agregarCliente(cliente);
                frmUsuarioExito frmUsuarioExito = new frmUsuarioExito();
                frmUsuarioExito.setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Throwable ex) {
            Logger.getLogger(frmCrearUsuario2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void textColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textColoniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearUsuario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPasswordField fieldContra;
    private javax.swing.JPasswordField fieldContraVerificar;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JTextField textCalle;
    private javax.swing.JTextField textColonia;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JTextField textNumCasa;
    // End of variables declaration//GEN-END:variables
}
