package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import GUI.*;
import com.mycompany.bancodominio.Cliente;
import java.text.SimpleDateFormat;

/**
 *
 * @author USER
 */
public class frmCalendario extends javax.swing.JFrame {
    Cliente cliente= new Cliente();
    
    /**
     * Creates new form frmInicioSesion
     */
    public frmCalendario() {
        initComponents();
    }
    
    public frmCalendario(Cliente cliente) {
        initComponents();
        this.cliente=cliente;
        textFecha.setText(cliente.getFechaNacimiento());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFecha = new javax.swing.JTextField();
        botonConfirmar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1084, 773));
        setMinimumSize(new java.awt.Dimension(1084, 773));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFecha.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        textFecha.setForeground(new java.awt.Color(102, 102, 102));
        textFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textFechaPropertyChange(evt);
            }
        });
        getContentPane().add(textFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 300, 90));

        botonConfirmar.setContentAreaFilled(false);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 410, 100));

        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 470, 280));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insertar Fecha.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        labelFondo.setMaximumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setMinimumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setPreferredSize(new java.awt.Dimension(1080, 773));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        cliente.setFechaNacimiento(textFecha.getText());
        frmCrearUsuario frmUsuario = new frmCrearUsuario(cliente);
        frmUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void textFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textFechaPropertyChange

    }//GEN-LAST:event_textFechaPropertyChange

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        if(evt.getOldValue() != null){
            SimpleDateFormat ff= new SimpleDateFormat("yyyy/MM/dd");
            textFecha.setText(ff.format(jCalendar1.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendar1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JTextField textFecha;
    // End of variables declaration//GEN-END:variables
}
