package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import GUI.*;
import com.mycompany.bancopersistencia.DTOS.CuentaDTO;

/**
 *
 * @author USER
 */
public class frmCrearCuentaExito extends javax.swing.JFrame {

    private CuentaDTO cuenta;

    /**
     * Creates new form frmInicioSesion
     */
    public frmCrearCuentaExito() {
        initComponents();
    }
    
    public frmCrearCuentaExito(CuentaDTO cuenta) {
        initComponents();
        this.cuenta=cuenta;
        labelNumCuenta.setText(cuenta.getNumeroCuenta());
        labelFechaApertura.setText(cuenta.getFechaApertura());      
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConfirmar = new javax.swing.JButton();
        labelFechaApertura = new javax.swing.JLabel();
        labelNumCuenta = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1084, 773));
        setMinimumSize(new java.awt.Dimension(1084, 773));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonConfirmar.setContentAreaFilled(false);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 440, 100));

        labelFechaApertura.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelFechaApertura.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(labelFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 210, 60));

        labelNumCuenta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumCuenta.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(labelNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 360, 60));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Crear Cuenta - Exito.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        labelFondo.setMaximumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setMinimumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setPreferredSize(new java.awt.Dimension(1080, 773));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        frmPerfil frmPerfil= new frmPerfil();
        frmPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuentaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuentaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuentaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuentaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearCuentaExito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JLabel labelFechaApertura;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNumCuenta;
    // End of variables declaration//GEN-END:variables
}
