/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Cuenta;
import com.mycompany.banconegocio.Controlador.Control;
import com.mycompany.bancopersistencia.excepciones.persistenciaException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author yohan
 */
public class frmDepositar extends javax.swing.JFrame {
    Cliente cliente;
    Cuenta cuenta;
    Control controlador = new Control();
    List<Cuenta> listaCuentas;
  
    
    /**
     * Creates new form frmDepositar
     */
    public frmDepositar() {
        initComponents();
    }
    
    public frmDepositar(Cliente cliente) {
        initComponents();
        this.cliente=cliente;
        try {
            listaCuentas = new ArrayList<>(controlador.mostrarCuentasDeCliente(cliente.getIdCliente()));
        } catch (persistenciaException ex) {
            Logger.getLogger(frmDepositar.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargarListaCuentas();
    }
    
    private void cargarListaCuentas(){
        for (int i = 0; i < listaCuentas.size(); i++) {
            comboBoxCuentaDepositar.addItem(listaCuentas.get(i).getNumeroCuenta());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxCuentaDepositar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textMonto = new javax.swing.JTextField();
        textConcepto = new javax.swing.JTextField();
        botonContinuar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxCuentaDepositar.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(comboBoxCuentaDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 450, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 50));

        textMonto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textMonto.setForeground(new java.awt.Color(102, 102, 102));
        textMonto.setToolTipText("");
        textMonto.setBorder(null);
        textMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMontoActionPerformed(evt);
            }
        });
        textMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMontoKeyTyped(evt);
            }
        });
        getContentPane().add(textMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 410, 50));

        textConcepto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textConcepto.setForeground(new java.awt.Color(102, 102, 102));
        textConcepto.setToolTipText("");
        textConcepto.setBorder(null);
        textConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConceptoActionPerformed(evt);
            }
        });
        getContentPane().add(textConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 430, 50));

        botonContinuar.setContentAreaFilled(false);
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 570, 80));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Depositar dinero.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMontoActionPerformed

    private void textConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConceptoActionPerformed

    
    //Admite solo valores numericos
    private void textMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMontoKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_textMontoKeyTyped

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        for (int i = 0; i < listaCuentas.size(); i++) {
            if(listaCuentas.get(i).getNumeroCuenta().equalsIgnoreCase((String) comboBoxCuentaDepositar.getSelectedItem())){
                cuenta= listaCuentas.get(i);
                break;
            }
        }
        if(controlador.depositar(cuenta, Integer.parseInt(textMonto.getText()))){
            frmDepositarExitoso frmDepositarExitoso = new frmDepositarExitoso(cuenta, textMonto.getText(), textConcepto.getText(), cliente);
            frmDepositarExitoso.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario(cliente);
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboBoxCuentaDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textConcepto;
    private javax.swing.JTextField textMonto;
    // End of variables declaration//GEN-END:variables
}
