/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;

/**
 *
 * @author yohan
 */
public class frmDatosUsuario extends javax.swing.JFrame {

    public frmDatosUsuario() {
        initComponents();
    }

    /**
     * Creates new form frmDatosUsuario
     *
     * @param cliente
     */
    public frmDatosUsuario(Cliente cliente) {
        initComponents();
        labelNombre.setText(cliente.getNombre());
        labelApellidoP.setText(cliente.getApellidoPaterno());
        labelApellidoM.setText(cliente.getApellidoMaterno());
        labelFechaNacimiento.setText(cliente.getFechaNacimiento());
        labelCalle.setText(cliente.getCalle());
        labelColonia.setText(cliente.getColonia());
        labelNombreCalle.setText(Integer.toString(cliente.getNumeroCasa()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelNombreCalle = new javax.swing.JLabel();
        labelApellidoP = new javax.swing.JLabel();
        labelApellidoM = new javax.swing.JLabel();
        labelFechaNacimiento = new javax.swing.JLabel();
        labelCalle = new javax.swing.JLabel();
        labelColonia = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 440, 40));
        getContentPane().add(labelNombreCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 440, 40));
        getContentPane().add(labelApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 440, 40));
        getContentPane().add(labelApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 440, 40));
        getContentPane().add(labelFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 440, 40));
        getContentPane().add(labelCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 440, 40));
        getContentPane().add(labelColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 440, 40));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 270, 60));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Informacion del Usuario.png"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmPerfil frmPerfil = new frmPerfil();
        frmPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelApellidoP;
    private javax.swing.JLabel labelCalle;
    private javax.swing.JLabel labelColonia;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCalle;
    // End of variables declaration//GEN-END:variables
}
