/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Cuenta;

/**
 *
 * @author yohan
 */
public class frmDepositarExitoso extends javax.swing.JFrame {

    private Cliente cliente;


    /**
     * Creates new form frmDepositarExitoso
     */
    public frmDepositarExitoso() {
        initComponents();
    }
    
    public frmDepositarExitoso(Cuenta cuenta, String monto, String concepto, Cliente cliente) {
        initComponents();
        this.cliente=cliente;
        labelConcepto.setText(concepto);
        labelCuenta.setText(cuenta.getNumeroCuenta());
        labelMonto.setText(monto);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMonto = new javax.swing.JLabel();
        labelConcepto = new javax.swing.JLabel();
        labelCuenta = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMonto.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        labelMonto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 260, 50));

        labelConcepto.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        labelConcepto.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(labelConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 380, 50));

        labelCuenta.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        labelCuenta.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(labelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 330, 50));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 600, 100));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Deposito Exitoso.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario(cliente);
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepositarExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepositarExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepositarExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepositarExitoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepositarExitoso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel labelConcepto;
    private javax.swing.JLabel labelCuenta;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelMonto;
    // End of variables declaration//GEN-END:variables
}
