/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Cuenta;
import com.mycompany.banconegocio.Controlador.Control;
import com.mycompany.bancopersistencia.excepciones.persistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yohan
 */
public class frmEliminarCuenta extends javax.swing.JFrame {

    Cliente cliente;
    Control controlador = new Control();

    /**
     * Creates new form frmEliminarCuenta
     */
    public frmEliminarCuenta() {
        initComponents();
        textNumeroCuenta.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    public frmEliminarCuenta(Cliente cliente) {
        initComponents();
        textNumeroCuenta.setBackground(new java.awt.Color(0, 0, 0, 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNumeroCuenta = new javax.swing.JTextField();
        botonConfirmar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textNumeroCuenta.setForeground(new java.awt.Color(102, 102, 102));
        textNumeroCuenta.setToolTipText("");
        textNumeroCuenta.setBorder(null);
        textNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(textNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 450, 40));

        botonConfirmar.setContentAreaFilled(false);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 380, 90));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 240, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eliminar Cuenta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1010, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroCuentaActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed

        try {
            if (controlador.consultarCuentaPorNumeroCuenta(textNumeroCuenta.getText()) == null) {
                JOptionPane.showMessageDialog(null, "No hay ninguna cuenta con ese numero de cuenta", "Error", JOptionPane.ERROR_MESSAGE);
                throw new persistenciaException("No hay ninguna cuenta con ese numero de cuenta");
            }
            Cuenta cuenta = controlador.consultarCuentaPorNumeroCuenta(textNumeroCuenta.getText());

            cuenta.setEstado("Cancelado");
            if (controlador.actualizarCliente(cliente) == true) {
                frmUsuarioExito frmUsuarioExito = new frmUsuarioExito();
                frmUsuarioExito.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (persistenciaException ex) {
            Logger.getLogger(frmCrearUsuario2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmPerfil frmPerfil = new frmPerfil(cliente);
        frmPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
