/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Usuario;
import com.mycompany.banconegocio.Controlador.Control;
import com.mycompany.bancopersistencia.DTOS.ClienteDTO;
import com.mycompany.bancopersistencia.DTOS.UsuarioDTO;
import com.mycompany.bancopersistencia.excepciones.persistenciaException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmInicioSesion extends javax.swing.JFrame {

    Control control = new Control();

    /**
     * Creates new form frmInicioSesion
     */
    public frmInicioSesion() {
        initComponents();
        textUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        fieldContra.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarSesion = new javax.swing.JButton();
        botonCrearUsuario = new javax.swing.JButton();
        botonRealizarRetiro = new javax.swing.JButton();
        textUsuario = new javax.swing.JTextField();
        fieldContra = new javax.swing.JPasswordField();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1084, 773));
        setMaximumSize(new java.awt.Dimension(1084, 773));
        setMinimumSize(new java.awt.Dimension(1084, 773));
        setPreferredSize(new java.awt.Dimension(1084, 773));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciarSesion.setContentAreaFilled(false);
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 480, 60));

        botonCrearUsuario.setContentAreaFilled(false);
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 480, 60));

        botonRealizarRetiro.setContentAreaFilled(false);
        botonRealizarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarRetiroActionPerformed(evt);
            }
        });
        getContentPane().add(botonRealizarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 480, 60));

        textUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textUsuario.setToolTipText("");
        textUsuario.setBorder(null);
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 450, 40));

        fieldContra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fieldContra.setBorder(null);
        getContentPane().add(fieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 450, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicio de Sesión.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        labelFondo.setMaximumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setMinimumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setPreferredSize(new java.awt.Dimension(1080, 773));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRealizarRetiroActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        frmCrearUsuario frmUsuario = new frmCrearUsuario();
        frmUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        try {
            String contra = new String(fieldContra.getPassword());
            ClienteDTO cliente = new ClienteDTO(contra, textUsuario.getText());
            Cliente clienteIngresado= control.consultarCliente(cliente);
            JOptionPane.showMessageDialog(null, "Se ha ingresado sesion correctamente", "Notificacion", JOptionPane.INFORMATION_MESSAGE);
            frmMenuUsuario frmMenuUsuario = new frmMenuUsuario(clienteIngresado);
            frmMenuUsuario.setVisible(true);
            this.setVisible(false);
        } catch (persistenciaException e) {
            JOptionPane.showMessageDialog(null, "Los datos ingresados no concuerdan con ningun usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRealizarRetiro;
    private javax.swing.JPasswordField fieldContra;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
