package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import GUI.*;
import com.mycompany.bancodominio.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class frmPerfil extends javax.swing.JFrame {

    Cliente cliente;

    /**
     * Creates new form frmInicioSesion
     */
    public frmPerfil() {
        initComponents();
    }

    /**
     * Creates new form frmInicioSesion
     */
    public frmPerfil(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearCuenta = new javax.swing.JButton();
        botonCerrarSesión = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonVerInformacion = new javax.swing.JButton();
        botonActualizarDatos = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1084, 773));
        setMinimumSize(new java.awt.Dimension(1084, 773));
        setResizable(false);
        setSize(new java.awt.Dimension(1084, 773));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCrearCuenta.setContentAreaFilled(false);
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 300, 50));

        botonCerrarSesión.setContentAreaFilled(false);
        botonCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesiónActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 300, 60));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 260, 80));

        botonVerInformacion.setContentAreaFilled(false);
        botonVerInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonVerInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 300, 60));

        botonActualizarDatos.setContentAreaFilled(false);
        botonActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 300, 60));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfil de Usuario.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        labelFondo.setMaximumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setMinimumSize(new java.awt.Dimension(1080, 773));
        labelFondo.setPreferredSize(new java.awt.Dimension(1080, 773));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        frmCrearCuenta frmCrearCuenta = new frmCrearCuenta(cliente);
        frmCrearCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    private void botonCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesiónActionPerformed
        // Mostrar un diálogo de confirmación
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión del usuario: " + cliente.getUsuario() + " ?", "Confirmación", JOptionPane.YES_NO_OPTION);
        // Verificar la opción seleccionada por el usuario
        if (opcion == JOptionPane.YES_OPTION) {
            frmInicioSesion frmInicio = new frmInicioSesion();
            frmInicio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_botonCerrarSesiónActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario();
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonVerInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerInformacionActionPerformed
        frmDatosUsuario frmDatosUsuario = new frmDatosUsuario(cliente);
        frmDatosUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVerInformacionActionPerformed

    private void botonActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDatosActionPerformed
        frmActualizarDatos frmActualizarDatos = new frmActualizarDatos(cliente);
        frmActualizarDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonActualizarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDatos;
    private javax.swing.JButton botonCerrarSesión;
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonVerInformacion;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
