/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancodominio.Cuenta;
import com.mycompany.banconegocio.Controlador.Control;
import com.mycompany.bancopersistencia.DTOS.RetiroDTO;
import com.mycompany.bancopersistencia.DTOS.TransferenciaDTO;
import com.mycompany.bancopersistencia.excepciones.persistenciaException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author yohan
 */
public class frmRetirarMenuExito extends javax.swing.JFrame {
    Cliente cliente;
    Cuenta cuenta;
    Control controlador = new Control();
    List<Cuenta> listaCuentas;
  
    
    /**
     * Creates new form frmDepositar
     */
    public frmRetirarMenuExito() {
        initComponents();
    }
    
    
    public frmRetirarMenuExito(Cliente cliente, RetiroDTO retiro) {
        initComponents();
        this.cliente=cliente;
        labelContra.setText(String.valueOf(retiro.getContraseña()));
        labelFolio.setText(String.valueOf(retiro.getFolio()));
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        labelFolio = new javax.swing.JLabel();
        labelFolio1 = new javax.swing.JLabel();
        labelFolio2 = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonContinuar.setContentAreaFilled(false);
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 300, 60));

        labelFolio.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelFolio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 400, 40));

        labelFolio1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelFolio1.setForeground(new java.awt.Color(255, 255, 255));
        labelFolio1.setText("jLabel2");
        getContentPane().add(labelFolio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 400, 40));

        labelFolio2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelFolio2.setForeground(new java.awt.Color(255, 255, 255));
        labelFolio2.setText("jLabel2");
        getContentPane().add(labelFolio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 400, 40));

        labelContra.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelContra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RetiroSinCuenta-MenuExitoso.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario(cliente);
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario(cliente);
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRetirarMenuExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRetirarMenuExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRetirarMenuExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRetirarMenuExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRetirarMenuExito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelFolio;
    private javax.swing.JLabel labelFolio1;
    private javax.swing.JLabel labelFolio2;
    // End of variables declaration//GEN-END:variables
}
