/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.bancodominio.Cliente;
import com.mycompany.bancopersistencia.DTOS.TransferenciaDTO;

/**
 *
 * @author yohan
 */
public class frmTransferenciaExito extends javax.swing.JFrame {

    TransferenciaDTO transferencia = new TransferenciaDTO();
    Cliente cliente;

    /**
     * Creates new form frmTransferenciaExito
     */
    public frmTransferenciaExito() {
        initComponents();
        String cuentaOrigen = transferencia.getCuentaOrigen();
        labelCuentaOrigen.setText(cuentaOrigen);
        String CuentaDestino = transferencia.getCuentaDestino();
        labelCuentaDestino.setText(CuentaDestino);
        String monto = Integer.toString(transferencia.getMonto());
        labelMonto.setText(monto);
    }

    public frmTransferenciaExito(TransferenciaDTO transferencia) {
        initComponents();
        this.transferencia = transferencia;

        String cuentaOrigen = transferencia.getCuentaOrigen();
        labelCuentaOrigen.setText(cuentaOrigen);
        String CuentaDestino = transferencia.getCuentaDestino();
        labelCuentaDestino.setText(CuentaDestino);
        String monto = Integer.toString(transferencia.getMonto());
        labelMonto.setText(monto);
    }

    public frmTransferenciaExito(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        String cuentaOrigen = transferencia.getCuentaOrigen();
        labelCuentaOrigen.setText(cuentaOrigen);
        String CuentaDestino = transferencia.getCuentaDestino();
        labelCuentaDestino.setText(CuentaDestino);
        String monto = Integer.toString(transferencia.getMonto());
        labelMonto.setText(monto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        botonPerfil = new javax.swing.JButton();
        labelCuentaDestino = new javax.swing.JLabel();
        labelMonto = new javax.swing.JLabel();
        labelCuentaOrigen = new javax.swing.JLabel();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cuenta destino:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 270, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cuenta origen:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Monto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 270, 30));

        botonRegresar.setContentAreaFilled(false);
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 430, 110));

        botonPerfil.setContentAreaFilled(false);
        botonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(botonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 110, 110));
        getContentPane().add(labelCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 430, 40));
        getContentPane().add(labelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 430, 40));
        getContentPane().add(labelCuentaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 430, 40));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transferir - Exitoso.png"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1120, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenuUsuario frmMenuUsuario = new frmMenuUsuario();
        frmMenuUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPerfilActionPerformed
        frmPerfil frmPerfil = new frmPerfil(cliente);
        frmPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransferenciaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransferenciaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransferenciaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransferenciaExito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransferenciaExito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JButton botonPerfil;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCuentaDestino;
    private javax.swing.JLabel labelCuentaOrigen;
    private javax.swing.JLabel labelMonto;
    // End of variables declaration//GEN-END:variables
}
